### PR TITLE
fixed the double typing issue. tested by entering a new entry and typ…

### LINKED ISSUE #121: able to double send a message
I think due to mining and the delay it is possible to quickly double enter and send two messages instead of the intended one.

### PR DESCRIPTION
**Pull request by Vanderscycle**
…ing as fast as humanly possible to get another entry. This is the last commit of this branch.

### CODE REVIEW

File: frontend/src/routes/Messages.svelte [hunk 1]
```diff
@@ -94,17 +94,15 @@ async function newMsg() {
...
-    //saving the data to the mongo db
-    await postNewMsg2Conversation(fullPayload);
-
     //websocket new entry
     socket.emit("chatToServer", {
       sender: userDomain,
       room: $selectedUser,
       message: chatMsg,
     });
     chatMsg = "";
```
Comment (brianorwhatever) [inline frontend/src/routes/Messages.svelte:103]: so does the `chatToServer` command here not persist the message to db? It feels like we're doing the same thing 2 ways here
